variable "access_key" {}
variable "secret_access_key" {}
variable "region" {}
variable "environment" {}
variable "project" {}
variable "create_type" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "private_subnet_az2_cidr" {}          
